from docx import Document #This imports the function Document from the python-docx extension
from docx.shared import Inches# This allows us to adjust the image size
import pyttsx3# This allows us to use a text to speech function

def speak(text):# text to speech class
    pyttsx3.speak(text)

document = Document()#This creates an actual word document


document.add_picture('IMG_20200812_100427733.jpg', 
width=Inches(2.0))#This allows us to import an image


#In this section we create variables to store the name, phone.no & email.
name = input('What is your name? ')
speak('Hello ' + name + ' how are you today? ')
phone_number = input('What is your phone number? ')
email = input('What is your email address? ')

document.add_paragraph(name + ' | ' + phone_number +' | ' + email)#Add words to the document

#A section to write about yourself
document.add_heading('ABOUT ME')
about_me = input('Tell me about yourself.')
document.add_paragraph(about_me)

#A work experience section

document.add_heading('WORK EXPERIENCE')
p=document.add_paragraph()

company = input('Enter company ')
from_date = input('From date ')
to_date = input('To date ')

p.add_run(company + ' ').bold = True#p.add_run, adds text to existing paragraphs
p.add_run(from_date + ' ' + to_date + '\n').italic = True#The \n will ensure that the next section starts on a new line.

experience_details = input('Describe your experience at ' + company )

p.add_run(experience_details)

#A section for more experiences
while True:
    has_more_experiences= input('Do you have more experiences? Yes or No.')

    if has_more_experiences.capitalize() == 'Yes':#As long as the answer is Yes, the for loop is going to keep asking this question after every entry.
        p=document.add_paragraph()

        company = input('Enter company  ')
        from_date = input('From date  ')
        to_date = input('To date  ')

        p.add_run(company + ' ').bold = True #p.add_run, adds text to existing paragraphs
        p.add_run(from_date + ' ' + to_date + '\n').italic = True#The \n will ensure that the next section starts on a new line.

        experience_details = input('Describe your experience at ' + company + ' ' )
        p.add_run(experience_details)
    else:#This allows us to exit the loop when the answer is no.
        break

#A section to show our skills

document.add_heading('SKILLS') 
skill= input('Enter skill')     
s=document.add_paragraph() 
s.style = 'List Bullet'

while True:
    has_more_skills=input('Do you have any skills? Yes or No')
    if has_more_skills.capitalize() == 'Yes':
        skill= input('Enter skill')     
        s=document.add_paragraph() 
        s.style = 'List Bullet'
    else:
        break

#A section for footer

section = document.sections[0]# This gets us access to the first section
footer=section.footer# This gets the footer from that first section
p = footer.paragraphs[0]# We're changing the paragraph to be the one from the footer section
p.text= "CV generated by Lennox Apudo using Python."# We're setting the text


speak('Congratulations ' + name + ' your CV is complete!!!')
    




document.save('cv.docx')#This saves our document
